# Extra logging for debugging purposes
verbose: true

# Parameters of which host and port to
# listen on for connections from admin interface
admin:
  host: 0.0.0.0
  port: 1338

# Parameters of which host and port to
# listen on for connections from the atm
bank:
  host: 0.0.0.0
  port: 1337

logging:
  log_path: /logs
  log_name: bank_server
